services:
  # Capa de BD
  db_redis:
    image: redis:alpine
    container_name: base_datos_salud

  # Capa de Lógica
  replica_1:
    build: ./app
    environment:
      - PUERTO=3001
    ports:
      - "3001:3001"
  replica_2:
    build: ./app
    environment:
      - PUERTO=3002
    ports:
      - "3002:3002"
  replica_3:
    build: ./app
    environment:
      - PUERTO=3003
    ports:
      - "3003:3003"
  
  # Capa de Red
  balanceador_carga_nginx:
    image: nginx:latest
    ports: 
      # Mapea el puerto 80 a la VM
      - "80:80"
    volumes:
      # Aquí se inyecta la configuración
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - replica_1
      - replica_2
      - replica_3