# El archivo mas importante, donde se tiene la configuración del balanceador de carga
upstream backend_salud {
    server replica_1:3001;
    server replica_2:3002;
    server replica_3:3003;
}

server {
    listen 80;
    location / {
        proxy_pass http://backend_salud;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}